Resources:
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
    # update AZ value and Image Id as per you choce if want to use as it is, use North V. (us-east-1a)
      AvailabilityZone: us-east-1a
      ImageId: ami-0742b4e673072066f
      InstanceType: t2.micro
